# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quizapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quizapp
  pod 'SwiftyJSON'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Alamofire', '~> 4.7'
end
